from numba import njit
    
@njit
def f_rhs(x, p, order=0, ind=None):
        
    ### This code was generated by Python.
    ### Eichenbaum, Rebelo and Trabandt Model with Resistant Virus Strain.
    
    # First order derivatives are employed in most of the models to compute Jacobian.
    # Higher order derivatives are used in nonlinear rational expectations models.
    
    from scipy.special import lambertw as LambertW
    from preprocessor.functions import Heaviside,Max,Min,Abs,DiracDelta
    from preprocessor.condition import IfThenElse,IfThen,Derivative,Subs,Positive,Negative,myzif

    import numpy as np
    from numpy import exp, sin, cos, tan, sqrt, sign, log
        
    # Initialize variables
    _xi_1 = 0 
    _xi_2 = 0 
    _xi_3 = 0 
    w__p1_ = x[3]
    rk__p1_ = x[4]
    ns__p1_ = x[17]
    ni__p1_ = x[18]
    nr__p1_ = x[19]
    cs__p1_ = x[20]
    ci__p1_ = x[21]
    cr__p1_ = x[22]
    lambtilde__p1_ = x[26]
    lamtau__p1_ = x[27]
    lami__p1_ = x[28]
    lams__p1_ = x[29]
    lamr__p1_ = x[30]
    pie__p1_ = x[34]
    F__p1_ = x[36]
    Kf__p1_ = x[37]
    wF__p1_ = x[43]
    rkF__p1_ = x[44]
    nsF__p1_ = x[57]
    niF__p1_ = x[58]
    nrF__p1_ = x[59]
    csF__p1_ = x[60]
    ciF__p1_ = x[61]
    crF__p1_ = x[62]
    lambtildeF__p1_ = x[66]
    lamtauF__p1_ = x[67]
    lamsF__p1_ = x[69]
    lamrF__p1_ = x[70]
    pieF__p1_ = x[74]
    FF__p1_ = x[76]
    KfF__p1_ = x[77]
    y__ = x[80]
    n__ = x[82]
    w__ = x[83]
    rk__ = x[84]
    x__ = x[85]
    c__ = x[86]
    i1__ = x[91]
    i2__ = x[92]
    r1__ = x[94]
    r2__ = x[95]
    v__ = x[96]
    ns__ = x[97]
    ni__ = x[98]
    nr__ = x[99]
    cs__ = x[100]
    ci__ = x[101]
    cr__ = x[102]
    tau__ = x[103]
    tau1__ = x[104]
    tau2__ = x[105]
    lambtilde__ = x[106]
    lamtau__ = x[107]
    lami__ = x[108]
    lams__ = x[109]
    lamr__ = x[110]
    Rb__ = x[113]
    pie__ = x[114]
    mc__ = x[115]
    F__ = x[116]
    Kf__ = x[117]
    pbreve__ = x[119]
    yF__ = x[120]
    nF__ = x[122]
    wF__ = x[123]
    rkF__ = x[124]
    xF__ = x[125]
    cF__ = x[126]
    iF1__ = x[131]
    iF2__ = x[132]
    rF1__ = x[134]
    rF2__ = x[135]
    vF__ = x[136]
    nsF__ = x[137]
    niF__ = x[138]
    nrF__ = x[139]
    csF__ = x[140]
    ciF__ = x[141]
    crF__ = x[142]
    tauF__ = x[143]
    tauF1__ = x[144]
    tauF2__ = x[145]
    lambtildeF__ = x[146]
    lamtauF__ = x[147]
    lamiF__ = x[148]
    lamsF__ = x[149]
    lamrF__ = x[150]
    RbF__ = x[153]
    pieF__ = x[154]
    mcF__ = x[155]
    FF__ = x[156]
    pbreveF__ = x[159]
    k__m1_ = x[161]
    s__m1_ = x[167]
    s1__m1_ = x[168]
    s2__m1_ = x[169]
    i1__m1_ = x[171]
    i2__m1_ = x[172]
    r1__m1_ = x[174]
    r2__m1_ = x[175]
    dd__m1_ = x[191]
    pop__m1_ = x[192]
    pbreve__m1_ = x[199]
    kF__m1_ = x[201]
    sF__m1_ = x[207]
    sF1__m1_ = x[208]
    sF2__m1_ = x[209]
    iF1__m1_ = x[211]
    iF2__m1_ = x[212]
    rF1__m1_ = x[214]
    rF2__m1_ = x[215]
    ddF__m1_ = x[231]
    popF__m1_ = x[232]
    pbreveF__m1_ = x[239]
    ei1__ = x[240]
    ei2__ = x[241]
    ed__ = x[242]

    # Set parameters
    xi = p[0]
    rpi = p[1]
    rx = p[2]
    gam = p[3]
    pi1 = p[4]
    pi2 = p[5]
    pi3 = p[6]
    mult = p[7]
    mult2 = p[8]
    pir = p[9]
    pid = p[10]
    betta = p[11]
    i_ini = p[12]
    d_ini = p[13]
    A = p[14]
    theta = p[15]
    alfa = p[16]
    inc_target = p[17]
    n_target = p[18]
    delta = p[19]
    g_ss = p[20]
    eta = p[21]
    xi_flex = p[22]
    pie_ss = p[23]
    rr_ss = p[24]
    Rb_ss = p[25]
    lockdown_policy = p[26]
    sigma = p[27]
    theta_lockdown = p[28]
    vaccination_policy = p[29]
    vaccination_rate = p[30]
    virus_resistant_strain = p[31]
    virus_variant_start = p[32]

    # Function:
    function = np.zeros(80)
    function[0] = A*n__**alfa*k__m1_**(1 - alfa)*pbreve__
    function[1] = w__**alfa*rk__**(1 - alfa)*alfa**(-alfa)*(1 - alfa)**(-(1 - alfa))/A
    function[2] = A*n__**(-1 + alfa)*mc__*alfa*k__m1_**(1 - alfa)
    function[3] = x__ + (1 - delta)*k__m1_
    function[4] = c__ + g_ss + x__
    function[5] = ni__*i1__m1_ + nr__*r1__m1_ + ns__*s1__m1_
    function[6] = ci__*i1__m1_ + cr__*r1__m1_ + cs__*s1__m1_
    function[7] = (1 - theta_lockdown*lockdown_policy)**2*(pi3*s1__m1_*i1__m1_ + pi1*cs__*ci__*s1__m1_*i1__m1_ + pi2*ni__*ns__*s1__m1_*i1__m1_)
    function[8] = (pi3*mult*s2__m1_*i2__m1_ + pi1*cs__*ci__*s2__m1_*i2__m1_ + pi2*ni__*ns__*s2__m1_*i2__m1_)*(1 - theta_lockdown*lockdown_policy)**2*virus_resistant_strain
    function[9] = tau1__ + tau2__
    function[10] = s1__m1_ - tau1__ - v__
    function[11] = s2__m1_ - tau2__
    function[12] = IfThenElse(s__m1_ - tau__ - v__, s__m1_ - tau__ - v__, 0)
    function[13] = ei1__ + i1__m1_ + tau1__ - (pid + pir)*i1__m1_
    function[14] = ei2__ + i2__m1_ + virus_resistant_strain*(tau2__ - i2__m1_*(pir + pid/mult2))
    function[15] = i1__ + i2__
    function[16] = r1__m1_ + v__ + pir*i1__m1_
    function[17] = r2__m1_ + pir*i2__m1_
    function[18] = r1__ + r2__
    function[19] = s1__m1_*vaccination_rate
    function[20] = dd__m1_ + ed__ + pid*i1__m1_ + pid*i2__m1_/mult2
    function[21] = pop__m1_ - pid*i1__m1_ - pid*i2__m1_/mult2
    function[22] = -cs__ + lamtau__ + (lambtilde__ - pi1*ci__*i1__m1_*lamtau__)**(-1)
    function[23] = lambtilde__**(-1)
    function[24] = lambtilde__**(-1)
    function[25] = (w__*lambtilde__ + pi2*ni__*i1__m1_*lamtau__)*(1 - theta_lockdown*lockdown_policy)/theta
    function[26] = w__*lambtilde__*(1 - theta_lockdown*lockdown_policy)/theta
    function[27] = w__*lambtilde__/theta
    function[28] = -lambtilde__ + rk__ + betta*(1 - delta + rk__p1_)*lambtilde__p1_
    function[29] = lams__ + lamtau__
    function[30] = cs__ + lams__p1_ - lams__/betta + lamtau__p1_*(pi3*i1__ + pi1*i1__*ci__p1_*cs__p1_ + pi2*i1__*ns__p1_*ni__p1_) + (-1/2)*theta*ns__p1_**2 + (-cs__p1_ + w__p1_*ns__p1_)*lambtilde__p1_ + log(cs__p1_)
    function[31] = ci__ - lami__/betta + pir*lamr__p1_ + (-1/2)*theta*ni__p1_**2 + (-ci__p1_ + w__p1_*ni__p1_)*lambtilde__p1_ + (1 - pid - pir)*lami__p1_ + log(ci__p1_)
    function[32] = cr__ + lamr__p1_ - lamr__/betta + (-1/2)*theta*nr__p1_**2 + (-cr__p1_ + w__p1_*nr__p1_)*lambtilde__p1_ + log(cr__p1_)
    function[33] = Rb__*betta*lambtilde__p1_/pie__p1_
    function[34] = Rb__/pie__p1_
    function[35] = xi*betta*Kf__p1_*pie__p1_**(gam/(-1 + gam)) + y__*gam*mc__*lambtilde__
    function[36] = y__*lambtilde__ + xi*betta*F__p1_*pie__p1_**((-1 + gam)**(-1))
    function[37] = -Kf__ + x__ + F__*((1 - xi*pie__**((-1 + gam)**(-1)))/(1 - xi))**(-(-1 + gam))
    function[38] = ((1 - xi)*((1 - xi*pie__**((-1 + gam)**(-1)))/(1 - xi))**gam + xi*pie__**(gam/(-1 + gam))/pbreve__m1_)**(-1)
    function[39] = rr_ss + rpi*log(pie__/pie_ss) + rx*log(y__/yF__)
    function[40] = A*nF__**alfa*pbreveF__*kF__m1_**(1 - alfa)
    function[41] = alfa**(-alfa)*wF__**alfa*(1 - alfa)**(-(1 - alfa))*rkF__**(1 - alfa)/A
    function[42] = A*nF__**(-1 + alfa)*alfa*mcF__*kF__m1_**(1 - alfa)
    function[43] = xF__ + (1 - delta)*kF__m1_
    function[44] = cF__ + g_ss + xF__
    function[45] = niF__*iF1__m1_ + nrF__*rF1__m1_ + nsF__*sF1__m1_
    function[46] = ciF__*iF1__m1_ + crF__*rF1__m1_ + csF__*sF1__m1_
    function[47] = (pi3*sF1__m1_*iF1__m1_ + pi1*csF__*ciF__*sF1__m1_*iF1__m1_ + pi2*niF__*nsF__*sF1__m1_*iF1__m1_)*(1 - theta_lockdown*lockdown_policy)**2
    function[48] = (1 - theta_lockdown*lockdown_policy)**2*virus_resistant_strain*(pi3*mult*sF2__m1_*iF2__m1_ + pi1*csF__*ciF__*sF2__m1_*iF2__m1_ + pi2*niF__*nsF__*sF2__m1_*iF2__m1_)
    function[49] = tauF1__ + tauF2__
    function[50] = sF1__m1_ - tauF1__ - vF__
    function[51] = sF2__m1_ - tauF2__
    function[52] = IfThenElse(sF__m1_ - tauF__ - vF__, sF__m1_ - tauF__ - vF__, 0)
    function[53] = ei1__ + iF1__m1_ + tauF1__ - (pid + pir)*iF1__m1_
    function[54] = ei2__ + iF2__m1_ + (tauF2__ - (pir + pid/mult2)*iF2__m1_)*virus_resistant_strain
    function[55] = iF1__ + iF2__
    function[56] = rF1__m1_ + vF__ + pir*iF1__m1_
    function[57] = rF2__m1_ + pir*iF2__m1_
    function[58] = rF1__ + rF2__
    function[59] = vaccination_rate*sF1__m1_
    function[60] = ddF__m1_ + ed__ + pid*iF1__m1_ + pid*iF2__m1_/mult2
    function[61] = popF__m1_ - pid*iF1__m1_ - pid*iF2__m1_/mult2
    function[62] = -csF__ + lamtauF__ + (lambtildeF__ - pi1*ciF__*lamtauF__*iF1__m1_)**(-1)
    function[63] = lambtildeF__**(-1)
    function[64] = lambtildeF__**(-1)
    function[65] = (wF__*lambtildeF__ + pi2*niF__*lamtauF__*iF1__m1_)*(1 - theta_lockdown*lockdown_policy)/theta
    function[66] = wF__*(1 - theta_lockdown*lockdown_policy)*lambtildeF__/theta
    function[67] = wF__*lambtildeF__/theta
    function[68] = -lambtildeF__ + rkF__ + betta*(1 - delta + rkF__p1_)*lambtildeF__p1_
    function[69] = lamsF__ + lamtauF__
    function[70] = csF__ + lamsF__p1_ - lamsF__/betta + (-1/2)*theta*nsF__p1_**2 + (-csF__p1_ + wF__p1_*nsF__p1_)*lambtildeF__p1_ + (pi3*iF1__ + pi1*iF1__*csF__p1_*ciF__p1_ + pi2*iF1__*niF__p1_*nsF__p1_)*lamtauF__p1_ + log(csF__p1_)
    function[71] = ciF__ - lamiF__/betta + pir*lamrF__p1_ + (-1/2)*theta*niF__p1_**2 + (-ciF__p1_ + wF__p1_*niF__p1_)*lambtildeF__p1_ + (1 - pid - pir)*lamiF__ + log(ciF__p1_)
    function[72] = crF__ + lamrF__p1_ - lamrF__/betta + (-1/2)*theta*nrF__p1_**2 + (-crF__p1_ + wF__p1_*nrF__p1_)*lambtildeF__p1_ + log(crF__p1_)
    function[73] = betta*RbF__*lambtildeF__p1_/pieF__p1_
    function[74] = RbF__/pieF__p1_
    function[75] = betta*pieF__p1_**(gam/(-1 + gam))*xi_flex*KfF__p1_ + gam*yF__*mcF__*lambtildeF__
    function[76] = yF__*lambtildeF__ + betta*pieF__p1_**((-1 + gam)**(-1))*xi_flex*FF__p1_
    function[77] = FF__*((1 - pieF__**((-1 + gam)**(-1))*xi_flex)/(1 - xi_flex))**(-(-1 + gam))
    function[78] = (((1 - pieF__**((-1 + gam)**(-1))*xi_flex)/(1 - xi_flex))**gam*(1 - xi_flex) + pieF__**(gam/(-1 + gam))*xi_flex/pbreveF__m1_)**(-1)
    function[79] = Rb_ss + rpi*log(pieF__/pie_ss)

    if order == 0:
        return function
    